name: Build App for macOS, Windows, and Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest  # Můžeme začít na Windows, pro Linux a macOS použijeme další běhy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run next-build

      - name: Build Windows App
        run: npx electron-builder --win --x64 --publish never

      - name: Build macOS App
        run: npx electron-builder --mac --x64 --publish never

      - name: Build Linux App
        run: npx electron-builder --linux --x64 --publish never

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDesktopAdmin-win
          path: dist/MyDesktopAdmin-*.exe

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDesktopAdmin-mac
          path: dist/MyDesktopAdmin-*.dmg

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDesktopAdmin-linux
          path: dist/MyDesktopAdmin-*.AppImage

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
